from django.shortcuts import render
def introduce(request):
    return render(request, 'webpage/introduce.html')
def exhibit(request):
    return render(request, 'webpage/exhibit.html')
def InheritorChart(request):
    return render(request, 'webpage/InheritorChart.html')
def traditionalSkill(request):
    return render(request, 'webpage/traditionalSkill.html')
def folkActivities(request):
    return render(request, 'webpage/folkActivities.html')
def operaAndMusic(request):
    return render(request, 'webpage/operaAndMusic.html')
def vedio(request):
    return render(request, 'webpage/vedio.html')
def ask(request):
    return render(request, 'webpage/ask.html')
def visualization(request):
    return render(request, 'webpage/visualization.html')
def kg_view(request):
    data_nodes = [
        {"name": "戴昌路", "des": "棕包脑国家级代表性传承人", "category": 0, "ethnicity": "瑶族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-131.html"},
        {"name": "王太保", "des": "临武傩戏国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-243.html"},
        {"name": "彭延坤", "des": "长沙弹词国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-433.html"},
        {"name": "左大玢", "des": "湘剧国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-215.html"},
        {"name": "辜红卫", "des": "新化山歌省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-136.html"},
        {"name": "盘金胜", "des": "瑶家坐歌堂省级代表性传承人", "category": 0, "ethnicity": "瑶族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-141.html"},
        {"name": "赵明华", "des": "瑶族长鼓舞国家级代表性传承人", "category": 0, "ethnicity": "瑶族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-123.html"},
        {"name": "姚大明", "des": "龙舞（九龙舞）国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-124.html"},
        {"name": "戴碧生", "des": "花瑶呜哇山歌国家级代表性传承人", "category": 0, "ethnicity": "瑶族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-107.html"},
        {"name": "张吉兵", "des": "赛龙舟省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-369.html"},
        {"name": "宁新义", "des": "攸县打铁水市级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-28.html"},
        {"name": "范忠茂", "des": "汝城香火龙省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-277.html"},
        {"name": "李阳波", "des": "抬阁（长乐抬阁故事会）国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-323.html"},
        {"name": "曾龙祥", "des": "客家火龙省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-329.html"},
        {"name": "李承锋", "des": "龙舞（板板龙灯）省级代表性传承人", "category": 0, "ethnicity": "土家族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-343.html"},
        {"name": "李运华", "des": "衡山拜龙省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-362.html"},
        {"name": "詹儒珍", "des": "马迹塘扎故事省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-377.html"},
        {"name": "姚仕彬", "des": "刀梯舞狮省级代表性传承人", "category": 0, "ethnicity": "侗族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-392.html"},
        {"name": "刘坤庭", "des": "长沙窑铜官陶瓷烧制技艺国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-1.html"},
        {"name": "曹明珠", "des": "石雕（菊花石雕）国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-427.html"},
        {"name": "黎承菊", "des": "土家族织锦技艺州级代表性传承人", "category": 0, "ethnicity": "土家族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-25.html"},
        {"name": "钟自奇", "des": "浏阳花炮制作技艺国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-4.html"},
        {"name": "柳建新", "des": "湘绣国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-82.html"},
        {"name": "杨洪江", "des": "苗族银饰锻制技艺州级代表性传承人", "category": 0, "ethnicity": "苗族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-32.html"},
        {"name": "曹冠明", "des": "溪砚制作工艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-40.html"},
        {"name": "吴渊", "des": "纸影戏影偶制作技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-11.html"},
        {"name": "刘如松", "des": "抬阁（珠梅故事会）省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-120.html"},
        {"name": "秦刚", "des": "八峒瑶族跳鼓坛省级代表性传承人", "category": 0, "ethnicity": "瑶族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-133.html"},
        {"name": "田志泽", "des": "龙舞（芷江孽龙）省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-312.html"},
        {"name": "兰立校", "des": "扎制吊龙省级代表性传承人", "category": 0, "ethnicity": "苗族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-315.html"},
        {"name": "吴牛振", "des": "苗族四月八国家级代表性传承人", "category": 0, "ethnicity": "苗族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-325.html"},
        {"name": "吴海深", "des": "苗族赶秋国家级代表性传承人", "category": 0, "ethnicity": "苗族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-327.html"},
        {"name": "姜盛文", "des": "赛龙舟省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-340.html"},
        {"name": "刘晓安", "des": "“衡南七巧龙舞”省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-350.html"},
        {"name": "易图毅", "des": "龙舞（雪峰断颈龙）省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-353.html"},
        {"name": "肖求进", "des": "龙舞（九市稻草龙）省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-360.html"},
        {"name": "鲁运生", "des": "益阳虾子起拱省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-382.html"},
        {"name": "刘齐跃", "des": "抬阁（珠梅抬故事）国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-328.html"},
        {"name": "陈范兴", "des": "抬阁（长乐抬阁故事会）国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-321.html"},
        {"name": "彭家齐", "des": "土家年省级表性传承人", "category": 0, "ethnicity": "土家族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-81.html"},
        {"name": "陈江柱", "des": "腊八豆制作技艺市级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-24.html"},
        {"name": "李科洪", "des": "李氏唢呐制作技艺市级非遗代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-26.html"},
        {"name": "谭智祥", "des": "浏阳夏布市级非遗代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-29.html"},
        {"name": "王良玉", "des": "湘西苗绣州级代表性传承人", "category": 0, "ethnicity": "苗族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-31.html"},
        {"name": "姚元飞", "des": "湘西竹编的州级传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-61.html"},
        {"name": "李胜夫", "des": "黑茶制作技艺（千两茶制作技艺）国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-18.html"},
        {"name": "刘杏益", "des": "黑茶制作技艺·茯砖茶制作技艺国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-19.html"},
        {"name": "肖益平", "des": "黑茶制作技艺（天尖茶制作技艺）省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-20.html"},
        {"name": "周国栋", "des": "沅江麻香糕传统手工技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-22.html"},
        {"name": "沈安国", "des": "益阳水竹凉席制作技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-49.html"},
        {"name": "刘正文", "des": "岳州扇制作技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-47.html"},
        {"name": "毛桃芝", "des": "毛氏菜制作技艺省级传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-12.html"},
        {"name": "张刚强", "des": "张新发槟榔制作技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-13.html"},
        {"name": "杨顺德", "des": "“杨裕兴”面条制作技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-9.html"},
        {"name": "龙米谷", "des": "苗族银饰锻制技艺国家级代表性传承人", "category": 0, "ethnicity": "苗族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-180.html"},
        {"name": "黎秋梅", "des": "土家族织锦技艺省级代表性传承人", "category": 0, "ethnicity": "土家族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-183.html"},
        {"name": "叶菊秀", "des": "土家族织锦技艺省级代表性传承人", "category": 0, "ethnicity": "土家族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-184.html"},
        {"name": "江林", "des": "江氏正骨术省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-171.html"},
        {"name": "黄蔚德", "des": "浏阳花炮制作技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-186.html"},
        {"name": "麻茂庭", "des": "苗族银饰锻制技艺国家级代表性传承人", "category": 0, "ethnicity": "苗族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-187.html"},
        {"name": "黄永平", "des": "醴陵釉下五彩瓷烧制技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-189.html"},
        {"name": "黄燕", "des": "黑茶制作技艺（茯砖茶制作技艺）省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-198.html"},
        {"name": "蒋振西", "des": "蓝印花布印染技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-201.html"},
        {"name": "刘志广", "des": "长沙窑铜官陶瓷烧制技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-202.html"},
        {"name": "万玉其", "des": "土家族吊脚楼营造技艺省级代表性传承人", "category": 0, "ethnicity": "土家族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-204.html"},
        {"name": "刘凡弟", "des": "滩头手工抄纸技艺省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-207.html"},
        {"name": "傅艺萍", "des": "昆曲项目国家级传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-134.html"},
        {"name": "陈世达", "des": "花瑶呜哇山歌省级代表性传承人", "category": 0, "ethnicity": "瑶族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-181.html"},
        {"name": "田隆信", "des": "土家族咚咚喹省级代表性传承人", "category": 0, "ethnicity": "土家族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-182.html"},
        {"name": "田采和", "des": "土家族咚咚喹省级代表性传承人", "category": 0, "ethnicity": "土家族",
         "url": "http://feiyi.wentiyun.cn/Exhibitor-185.html"},
        {"name": "石喜富", "des": "芦笙音乐（侗族芦笙）省级代表性传承人", "category": 0, "ethnicity": "侗族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-188.html"},
        {"name": "李福国", "des": "傩戏（辰州傩戏）国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-191.html"},
        {"name": "聂满娥", "des": "傩戏（沅陵辰州傩戏）国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-194.html"},
        {"name": "龙开春", "des": "傩戏（侗族傩戏）国家级代表性传承人", "category": 0, "ethnicity": "侗族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-197.html"},
        {"name": "杨建娥", "des": "《花鼓戏》国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-213.html"},
        {"name": "杜美霜", "des": "《花鼓戏》国家级传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-214.html"},
        {"name": "陈岳林", "des": "渔歌（洞庭渔歌）省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-219.html"},
        {"name": "刘登雄", "des": "湖南祁剧国家级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-220.html"},
        {"name": "李桃英", "des": "嘉禾伴嫁歌省级代表性传承人", "category": 0, "ethnicity": "汉族",
         "url": "http://www.hunanfeiyi.cn/Exhibitor-221.html"},
        {"name": "棕包脑", "des": "瑶族舞蹈", "category": 1},
        {"name": "临武傩戏", "des": "傩戏", "category": 1},
        {"name": "长沙弹词", "des": "曲艺", "category": 1},
        {"name": "湘剧", "des": "戏曲", "category": 1},
        {"name": "新化山歌", "des": "山歌", "category": 1},
        {"name": "瑶家坐歌堂", "des": "瑶族音乐", "category": 1},
        {"name": "瑶族长鼓舞", "des": "瑶族舞蹈", "category": 1},
        {"name": "龙舞", "des": "龙舞", "category": 1},
        {"name": "花瑶呜哇山歌", "des": "瑶族山歌", "category": 1},
        {"name": "赛龙舟", "des": "民俗活动", "category": 1},
        {"name": "攸县打铁水", "des": "民俗活动", "category": 1},
        {"name": "汝城香火龙", "des": "民俗活动", "category": 1},
        {"name": "抬阁", "des": "民俗活动", "category": 1},
        {"name": "客家火龙", "des": "民俗活动", "category": 1},
        {"name": "马迹塘扎故事", "des": "民俗活动", "category": 1},
        {"name": "刀梯舞狮", "des": "舞狮", "category": 1},
        {"name": "长沙窑铜官陶瓷烧制技艺", "des": "陶瓷技艺", "category": 1},
        {"name": "石雕", "des": "石雕技艺", "category": 1},
        {"name": "土家族织锦技艺", "des": "织锦技艺", "category": 1},
        {"name": "浏阳花炮制作技艺", "des": "花炮制作技艺", "category": 1},
        {"name": "湘绣", "des": "刺绣技艺", "category": 1},
        {"name": "苗族银饰锻制技艺", "des": "银饰锻制技艺", "category": 1},
        {"name": "溪砚制作工艺", "des": "砚台制作技艺", "category": 1},
        {"name": "纸影戏影偶制作技艺", "des": "影偶制作技艺", "category": 1},
        {"name": "八峒瑶族跳鼓坛", "des": "跳鼓坛", "category": 1},
        {"name": "扎制吊龙", "des": "吊龙", "category": 1},
        {"name": "苗族四月八", "des": "四月八", "category": 1},
        {"name": "苗族赶秋", "des": "赶秋", "category": 1},
        {"name": "益阳虾子起拱", "des": "虾子起拱", "category": 1},
        {"name": "土家年", "des": "土家年", "category": 1},
        {"name": "腊八豆", "des": "制作技艺", "category": 1},
        {"name": "李氏唢呐", "des": "唢呐制作技艺", "category": 1},
        {"name": "浏阳夏布", "des": "传统布艺技艺", "category": 1},
        {"name": "湘西苗绣", "des": "苗族刺绣技艺", "category": 1},
        {"name": "湘西竹编", "des": "竹编技艺", "category": 1},
        {"name": "黑茶", "des": "黑茶制作技艺", "category": 1},
        {"name": "麻香糕", "des": "传统糕点技艺", "category": 1},
        {"name": "水竹凉席", "des": "凉席制作技艺", "category": 1},
        {"name": "岳州扇", "des": "扇子制作技艺", "category": 1},
        {"name": "毛氏菜", "des": "菜肴制作技艺", "category": 1},
        {"name": "槟榔", "des": "槟榔制作技艺", "category": 1},
        {"name": "杨裕兴面条", "des": "面条制作技艺", "category": 1},
        {"name": "苗族银饰", "des": "苗族银饰制作技艺", "category": 1},
        {"name": "土家族织锦", "des": "土家族织锦技艺", "category": 1},
        {"name": "浏阳花炮", "des": "花炮制作技艺", "category": 1},
        {"name": "醴陵釉下五彩瓷", "des": "陶瓷烧制技艺", "category": 1},
        {"name": "蓝印花布", "des": "蓝印花布技艺", "category": 1},
        {"name": "铜官陶瓷", "des": "陶瓷烧制技艺", "category": 1},
        {"name": "吊脚楼营造", "des": "土家族吊脚楼建造技艺", "category": 1},
        {"name": "滩头抄纸", "des": "手工纸制作技艺", "category": 1},
        {"name": "江氏正骨术", "des": "江氏正骨术", "category": 1},
        {"name": "昆曲", "des": "昆曲", "category": 1},
        {"name": "土家族咚咚喹", "des": "土家族传统音乐", "category": 1},
        {"name": "芦笙音乐", "des": "侗族芦笙音乐", "category": 1},
        {"name": "辰州傩戏", "des": "傩戏", "category": 1},
        {"name": "沅陵辰州傩戏", "des": "傩戏", "category": 1},
        {"name": "侗族傩戏", "des": "侗族傩戏", "category": 1},
        {"name": "花鼓戏", "des": "花鼓戏", "category": 1},
        {"name": "洞庭渔歌", "des": "渔歌", "category": 1},
        {"name": "湖南祁剧", "des": "戏曲", "category": 1},
        {"name": "嘉禾伴嫁歌", "des": "民间歌曲", "category": 1},
    ]
    data_links = [
        {"source": "戴昌路", "target": "棕包脑", "name": "传承"},
        {"source": "王太保", "target": "临武傩戏", "name": "传承"},
        {"source": "彭延坤", "target": "长沙弹词", "name": "传承"},
        {"source": "左大玢", "target": "湘剧", "name": "传承"},
        {"source": "辜红卫", "target": "新化山歌", "name": "传承"},
        {"source": "盘金胜", "target": "瑶家坐歌堂", "name": "传承"},
        {"source": "赵明华", "target": "瑶族长鼓舞", "name": "传承"},
        {"source": "姚大明", "target": "龙舞", "name": "传承"},
        {"source": "戴碧生", "target": "花瑶呜哇山歌", "name": "传承"},
        {"source": "张吉兵", "target": "赛龙舟", "name": "传承"},
        {"source": "宁新义", "target": "攸县打铁水", "name": "传承"},
        {"source": "范忠茂", "target": "汝城香火龙", "name": "传承"},
        {"source": "李阳波", "target": "抬阁", "name": "传承"},
        {"source": "刘如松", "target": "抬阁", "name": "传承"},
        {"source": "曾龙祥", "target": "客家火龙", "name": "传承"},
        {"source": "李承锋", "target": "板板龙灯", "name": "传承"},
        {"source": "李运华", "target": "衡山拜龙", "name": "传承"},
        {"source": "詹儒珍", "target": "马迹塘扎故事", "name": "传承"},
        {"source": "姚仕彬", "target": "刀梯舞狮", "name": "传承"},
        {"source": "刘坤庭", "target": "长沙窑铜官陶瓷烧制技艺", "name": "传承"},
        {"source": "曹明珠", "target": "石雕", "name": "传承"},
        {"source": "黎承菊", "target": "土家族织锦技艺", "name": "传承"},
        {"source": "钟自奇", "target": "浏阳花炮制作技艺", "name": "传承"},
        {"source": "柳建新", "target": "湘绣", "name": "传承"},
        {"source": "杨洪江", "target": "苗族银饰锻制技艺", "name": "传承"},
        {"source": "曹冠明", "target": "溪砚制作工艺", "name": "传承"},
        {"source": "吴渊", "target": "纸影戏影偶制作技艺", "name": "传承"},
        {"source": "伍芬邓", "target": "新化山歌", "name": "传承"},
        {"source": "秦刚", "target": "八峒瑶族跳鼓坛", "name": "传承"},
        {"source": "田志泽", "target": "龙舞", "name": "传承"},
        {"source": "兰立校", "target": "扎制吊龙", "name": "传承"},
        {"source": "李阳波", "target": "抬阁", "name": "传承"},
        {"source": "吴牛振", "target": "苗族四月八", "name": "传承"},
        {"source": "吴海深", "target": "苗族赶秋", "name": "传承"},
        {"source": "姜盛文", "target": "赛龙舟", "name": "传承"},
        {"source": "刘晓安", "target": "龙舞", "name": "传承"},
        {"source": "易图毅", "target": "龙舞", "name": "传承"},
        {"source": "肖求进", "target": "龙舞", "name": "传承"},
        {"source": "鲁运生", "target": "益阳虾子起拱", "name": "传承"},
        {"source": "刘齐跃", "target": "抬阁", "name": "传承"},
        {"source": "陈范兴", "target": "抬阁", "name": "传承"},
        {"source": "彭家齐", "target": "土家年", "name": "传承"},
        {"source": "陈江柱", "target": "腊八豆", "name": "传承"},
        {"source": "李科洪", "target": "李氏唢呐", "name": "传承"},
        {"source": "谭智祥", "target": "浏阳夏布", "name": "传承"},
        {"source": "王良玉", "target": "湘西苗绣", "name": "传承"},
        {"source": "姚元飞", "target": "湘西竹编", "name": "传承"},
        {"source": "李胜夫", "target": "黑茶", "name": "传承"},
        {"source": "刘杏益", "target": "黑茶", "name": "传承"},
        {"source": "肖益平", "target": "黑茶", "name": "传承"},
        {"source": "周国栋", "target": "麻香糕", "name": "传承"},
        {"source": "沈安国", "target": "水竹凉席", "name": "传承"},
        {"source": "刘正文", "target": "岳州扇", "name": "传承"},
        {"source": "毛桃芝", "target": "毛氏菜", "name": "传承"},
        {"source": "张刚强", "target": "槟榔", "name": "传承"},
        {"source": "杨顺德", "target": "杨裕兴面条", "name": "传承"},
        {"source": "龙米谷", "target": "苗族银饰", "name": "传承"},
        {"source": "黎秋梅", "target": "土家族织锦", "name": "传承"},
        {"source": "叶菊秀", "target": "土家族织锦", "name": "传承"},
        {"source": "江林", "target": "江氏正骨术", "name": "传承"},
        {"source": "黄蔚德", "target": "浏阳花炮", "name": "传承"},
        {"source": "麻茂庭", "target": "苗族银饰", "name": "传承"},
        {"source": "黄永平", "target": "醴陵釉下五彩瓷", "name": "传承"},
        {"source": "黄燕", "target": "黑茶", "name": "传承"},
        {"source": "蒋振西", "target": "蓝印花布", "name": "传承"},
        {"source": "刘志广", "target": "铜官陶瓷", "name": "传承"},
        {"source": "万玉其", "target": "吊脚楼营造", "name": "传承"},
        {"source": "刘凡弟", "target": "滩头抄纸", "name": "传承"},
        {"source": "江林", "target": "江氏正骨术", "name": "传承"},
        {"source": "傅艺萍", "target": "昆曲", "name": "传承"},
        {"source": "陈世达", "target": "花瑶呜哇山歌", "name": "传承"},
        {"source": "田隆信", "target": "土家族咚咚喹", "name": "传承"},
        {"source": "田采和", "target": "土家族咚咚喹", "name": "传承"},
        {"source": "石喜富", "target": "芦笙音乐", "name": "传承"},
        {"source": "李福国", "target": "辰州傩戏", "name": "传承"},
        {"source": "聂满娥", "target": "沅陵辰州傩戏", "name": "传承"},
        {"source": "龙开春", "target": "侗族傩戏", "name": "传承"},
        {"source": "杨建娥", "target": "花鼓戏", "name": "传承"},
        {"source": "杜美霜", "target": "花鼓戏", "name": "传承"},
        {"source": "陈岳林", "target": "洞庭渔歌", "name": "传承"},
        {"source": "刘登雄", "target": "湖南祁剧", "name": "传承"},
        {"source": "李桃英", "target": "嘉禾伴嫁歌", "name": "传承"},
    ]
    selected_filters = {
        'ethnicity': request.GET.get('ethnicity', 'off') == 'on',
        'category': request.GET.get('category', 'off') == 'on',
        'works': request.GET.get('works', 'off') == 'on',
    }
    if selected_filters['ethnicity']:
        data_nodes += [
            {"name": "汉族", "des": "汉族", "category": 4},
            {"name": "土家族", "des": "土家族", "category": 4},
            {"name": "侗族", "des": "侗族", "category": 4},
            {"name": "苗族", "des": "苗族", "category": 4},
            {"name": "瑶族", "des": "瑶族", "category": 4},
        ]
        data_links += [
            {"source": "戴昌路", "target": "瑶族", "name": "属于瑶族"},
            {"source": "盘金胜", "target": "瑶族", "name": "属于瑶族"},
            {"source": "赵明华", "target": "瑶族", "name": "属于瑶族"},
            {"source": "戴碧生", "target": "瑶族", "name": "属于瑶族"},
            {"source": "王太保", "target": "汉族", "name": "属于汉族"},
            {"source": "彭延坤", "target": "汉族", "name": "属于汉族"},
            {"source": "左大玢", "target": "汉族", "name": "属于汉族"},
            {"source": "辜红卫", "target": "汉族", "name": "属于汉族"},
            {"source": "姚大明", "target": "汉族", "name": "属于汉族"},
            {"source": "张吉兵", "target": "汉族", "name": "属于汉族"},
            {"source": "宁新义", "target": "汉族", "name": "属于汉族"},
            {"source": "范忠茂", "target": "汉族", "name": "属于汉族"},
            {"source": "李阳波", "target": "汉族", "name": "属于汉族"},
            {"source": "曾龙祥", "target": "汉族", "name": "属于汉族"},
            {"source": "李运华", "target": "汉族", "name": "属于汉族"},
            {"source": "詹儒珍", "target": "汉族", "name": "属于汉族"},
            {"source": "刘坤庭", "target": "汉族", "name": "属于汉族"},
            {"source": "曹明珠", "target": "汉族", "name": "属于汉族"},
            {"source": "钟自奇", "target": "汉族", "name": "属于汉族"},
            {"source": "柳建新", "target": "汉族", "name": "属于汉族"},
            {"source": "曹冠明", "target": "汉族", "name": "属于汉族"},
            {"source": "吴渊", "target": "汉族", "name": "属于汉族"},
            {"source": "刘如松", "target": "汉族", "name": "属于汉族"},
            {"source": "伍芬邓", "target": "汉族", "name": "属于汉族"},
            {"source": "秦刚", "target": "瑶族", "name": "属于瑶族"},
            {"source": "田志泽", "target": "汉族", "name": "属于汉族"},
            {"source": "兰立校", "target": "苗族", "name": "属于苗族"},
            {"source": "吴牛振", "target": "苗族", "name": "属于苗族"},
            {"source": "吴海深", "target": "苗族", "name": "属于苗族"},
            {"source": "姜盛文", "target": "汉族", "name": "属于汉族"},
            {"source": "刘晓安", "target": "汉族", "name": "属于汉族"},
            {"source": "易图毅", "target": "汉族", "name": "属于汉族"},
            {"source": "肖求进", "target": "汉族", "name": "属于汉族"},
            {"source": "鲁运生", "target": "汉族", "name": "属于汉族"},
            {"source": "刘齐跃", "target": "汉族", "name": "属于汉族"},
            {"source": "陈范兴", "target": "汉族", "name": "属于汉族"},
            {"source": "彭家齐", "target": "土家族", "name": "属于土家族"},
            {"source": "黎承菊", "target": "土家族", "name": "属于土家族"},
            {"source": "李承锋", "target": "土家族", "name": "属于土家族"},
            {"source": "姚仕彬", "target": "侗族", "name": "属于侗族"},
            {"source": "杨洪江", "target": "苗族", "name": "属于苗族"},
            {"source": "陈江柱", "target": "汉族", "name": "属于汉族"},
            {"source": "李科洪", "target": "汉族", "name": "属于汉族"},
            {"source": "谭智祥", "target": "汉族", "name": "属于汉族"},
            {"source": "王良玉", "target": "苗族", "name": "属于苗族"},
            {"source": "姚元飞", "target": "汉族", "name": "属于汉族"},
            {"source": "李胜夫", "target": "汉族", "name": "属于汉族"},
            {"source": "刘杏益", "target": "汉族", "name": "属于汉族"},
            {"source": "肖益平", "target": "汉族", "name": "属于汉族"},
            {"source": "周国栋", "target": "汉族", "name": "属于汉族"},
            {"source": "沈安国", "target": "汉族", "name": "属于汉族"},
            {"source": "刘正文", "target": "汉族", "name": "属于汉族"},
            {"source": "毛桃芝", "target": "汉族", "name": "属于汉族"},
            {"source": "张刚强", "target": "汉族", "name": "属于汉族"},
            {"source": "杨顺德", "target": "汉族", "name": "属于汉族"},
            {"source": "龙米谷", "target": "苗族", "name": "属于苗族"},
            {"source": "黎秋梅", "target": "土家族", "name": "属于土家族"},
            {"source": "叶菊秀", "target": "土家族", "name": "属于土家族"},
            {"source": "江林", "target": "汉族", "name": "属于汉族"},
            {"source": "黄蔚德", "target": "汉族", "name": "属于汉族"},
            {"source": "麻茂庭", "target": "苗族", "name": "属于苗族"},
            {"source": "黄永平", "target": "汉族", "name": "属于汉族"},
            {"source": "黄燕", "target": "汉族", "name": "属于汉族"},
            {"source": "蒋振西", "target": "汉族", "name": "属于汉族"},
            {"source": "刘志广", "target": "汉族", "name": "属于汉族"},
            {"source": "万玉其", "target": "土家族", "name": "属于土家族"},
            {"source": "刘凡弟", "target": "汉族", "name": "属于汉族"},
            {"source": "傅艺萍", "target": "汉族", "name": "属于汉族"},
            {"source": "陈世达", "target": "瑶族", "name": "属于瑶族"},
            {"source": "田隆信", "target": "土家族", "name": "属于土家族"},
            {"source": "田采和", "target": "土家族", "name": "属于土家族"},
            {"source": "石喜富", "target": "侗族", "name": "属于侗族"},
            {"source": "李福国", "target": "汉族", "name": "属于汉族"},
            {"source": "聂满娥", "target": "汉族", "name": "属于汉族"},
            {"source": "龙开春", "target": "侗族", "name": "属于侗族"},
            {"source": "杨建娥", "target": "汉族", "name": "属于汉族"},
            {"source": "杜美霜", "target": "汉族", "name": "属于汉族"},
            {"source": "陈岳林", "target": "汉族", "name": "属于汉族"},
            {"source": "刘登雄", "target": "汉族", "name": "属于汉族"},
            {"source": "李桃英", "target": "汉族", "name": "属于汉族"},
        ]
    if selected_filters['category']:
        data_nodes += [
            {"name": "国家级传承人", "des": "国家级传承人", "category": 4},
            {"name": "省级传承人", "des": "省级传承人", "category": 4},
            {"name": "市级传承人", "des": "市级传承人", "category": 4},
            {"name": "州级传承人", "des": "州级传承人", "category": 4},
        ]
        data_links += [
            {"source": "戴昌路", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "王太保", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "彭延坤", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "左大玢", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "赵明华", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "姚大明", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "戴碧生", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "李阳波", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "刘坤庭", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "曹明珠", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "钟自奇", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "柳建新", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "杨洪江", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "曹冠明", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "吴渊", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "辜红卫", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "盘金胜", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "张吉兵", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "范忠茂", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "曾龙祥", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "李承锋", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "李运华", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "詹儒珍", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "姚仕彬", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "傅艺萍", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "李福国", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "聂满娥", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "龙开春", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "杨建娥", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "杜美霜", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "刘登雄", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "陈世达", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "田隆信", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "田采和", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "石喜富", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "陈岳林", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "李桃英", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "宁新义", "target": "市级传承人", "name": "属于市级传承人"},
            {"source": "黎承菊", "target": "州级传承人", "name": "属于州级传承人"},
            {"source": "刘如松", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "伍芬邓", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "秦刚", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "田志泽", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "兰立校", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "姜盛文", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "刘晓安", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "易图毅", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "肖求进", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "鲁运生", "target": "省级传承人", "name": "属于省级代表性传承人"},
            {"source": "彭家齐", "target": "省级传承人", "name": "属于省级表性传承人"},
            {"source": "李阳波", "target": "国家级传承人", "name": "属于国家级代表性传承人"},
            {"source": "吴牛振", "target": "国家级传承人", "name": "属于国家级代表性传承人"},
            {"source": "吴海深", "target": "国家级传承人", "name": "属于国家级代表性传承人"},
            {"source": "刘齐跃", "target": "国家级传承人", "name": "属于国家级代表性传承人"},
            {"source": "陈范兴", "target": "国家级传承人", "name": "属于国家级代表性传承人"},
            {"source": "陈江柱", "target": "市级传承人", "name": "属于市级传承人"},
            {"source": "李科洪", "target": "市级传承人", "name": "属于市级传承人"},
            {"source": "谭智祥", "target": "市级传承人", "name": "属于市级传承人"},
            {"source": "王良玉", "target": "州级传承人", "name": "属于州级传承人"},
            {"source": "姚元飞", "target": "州级传承人", "name": "属于州级传承人"},
            {"source": "李胜夫", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "刘杏益", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "肖益平", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "周国栋", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "沈安国", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "刘正文", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "毛桃芝", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "张刚强", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "杨顺德", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "龙米谷", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "黎秋梅", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "叶菊秀", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "江林", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "黄蔚德", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "麻茂庭", "target": "国家级传承人", "name": "属于国家级传承人"},
            {"source": "黄永平", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "黄燕", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "蒋振西", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "刘志广", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "万玉其", "target": "省级传承人", "name": "属于省级传承人"},
            {"source": "刘凡弟", "target": "省级传承人", "name": "属于省级传承人"},
        ]
    if selected_filters['works']:
        data_nodes += [
            {"name": "民俗活动", "des": "民俗活动", "category": 4},
            {"name": "戏曲与音乐", "des": "戏曲与音乐", "category": 4},
            {"name": "传统技艺", "des": "传统技艺", "category": 4},
        ]
        data_links += [
            {"source": "棕包脑", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "临武傩戏", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "长沙弹词", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "湘剧", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "新化山歌", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "瑶家坐歌堂", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "瑶族长鼓舞", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "龙舞", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "花瑶呜哇山歌", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "赛龙舟", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "攸县打铁水", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "汝城香火龙", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "抬阁", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "客家火龙", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "板板龙灯", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "衡山拜龙", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "马迹塘扎故事", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "刀梯舞狮", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "抬阁（珠梅故事会）", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "新化山歌", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "八峒瑶族跳鼓坛", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "扎制吊龙", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "抬阁（长乐抬阁故事会）", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "苗族四月八", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "苗族赶秋", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "赛龙舟", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "益阳虾子起拱", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "抬阁（珠梅抬故事）", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "抬阁（长乐抬阁故事会）", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "土家年", "target": "民俗活动", "name": "属于民俗活动"},
            {"source": "长沙窑铜官陶瓷烧制技艺", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "石雕", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "土家族织锦技艺", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "浏阳花炮制作技艺", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "湘绣", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "苗族银饰锻制技艺", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "溪砚制作工艺", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "纸影戏影偶制作技艺", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "腊八豆", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "李氏唢呐", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "浏阳夏布", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "湘西苗绣", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "湘西竹编", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "黑茶", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "麻香糕", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "水竹凉席", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "岳州扇", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "毛氏菜", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "槟榔", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "杨裕兴面条", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "苗族银饰", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "土家族织锦", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "浏阳花炮", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "醴陵釉下五彩瓷", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "蓝印花布", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "铜官陶瓷", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "吊脚楼营造", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "滩头抄纸", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "江氏正骨术", "target": "传统技艺", "name": "属于传统技艺"},
            {"source": "昆曲", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "花瑶呜哇山歌", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "土家族咚咚喹", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "芦笙音乐", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "辰州傩戏", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "侗族傩戏", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "沅陵辰州傩戏", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "花鼓戏", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "洞庭渔歌", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "洞庭渔歌", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "湖南祁剧", "target": "戏曲与音乐", "name": "属于戏曲与音乐"},
            {"source": "嘉禾伴嫁歌", "target": "戏曲与音乐", "name": "属于戏曲与音乐"}
        ]
    data_json = {
        "data_nodes": data_nodes,
        "data_links": data_links,
        "selected_filters": selected_filters,
    }
    return render(request, 'webpage/kg_view.html', data_json)
